# Generated by Django 4.2 on 2023-04-07 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("summary", models.CharField(max_length=500)),
                (
                    "release_year",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1300),
                            django.core.validators.MaxValueValidator(1500),
                        ]
                    ),
                ),
                (
                    "rate",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("duration", models.SmallIntegerField()),
                ("image", models.ImageField(upload_to="")),
                ("genre", models.ManyToManyField(to="namava.genre")),
            ],
        ),
    ]
