# Generated by Django 4.2 on 2023-04-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("namava", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
