# Generated by Django 4.2 on 2023-04-07 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("namava", "0003_alter_movie_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="image",
        ),
    ]
