# Generated by Django 4.2 on 2023-04-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("namava", "0004_remove_movie_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="link",
            field=models.URLField(default="http://www.google.com"),
            preserve_default=False,
        ),
    ]
