# Generated by Django 4.2 on 2023-04-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("namava", "0005_movie_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rate",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_year",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="summary",
            field=models.TextField(max_length=500),
        ),
    ]
