# Generated by Django 4.2 on 2023-04-08 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("namava", "0007_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="namava.movie",
            ),
        ),
    ]
