# Generated by Django 4.2 on 2023-04-08 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("namava", "0008_alter_image_movie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="link",
        ),
    ]
