# Generated by Django 4.2 on 2023-04-08 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("namava", "0009_remove_movie_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="namava.movie",
            ),
        ),
    ]
