# Generated by Django 4.2 on 2023-04-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("namava", "0010_alter_image_movie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
