# Generated by Django 4.2 on 2023-04-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("namava", "0011_cast"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="cast",
            field=models.ManyToManyField(to="namava.cast"),
        ),
    ]
