# Generated by Django 4.2 on 2023-04-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("namava", "0012_movie_cast"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.CharField(default="A", max_length=50),
            preserve_default=False,
        ),
    ]
